### ISSUE TITLE
ytm not playing tracks when logged in

### ISSUE THREAD

**Issue by 1dirtypanda** [patrickkfkan/volumio-ytmusic#1]
volumio 3.396
ytmusic 0.1.8 and 0.1.7

when I am signed out of my account - ytm plays fine.
when I log into my account - ytm does not play music. example error log is below. 

info: [ytmusic-play] clearAddPlayTrack(): ytmusic/video@videoId=_ih7Plsc1r0@explodeTrackData=%7B%22videoId%22%3A%22_ih7Plsc1r0%22%2C%22title%22%3A%22Sucker%20Train%20Blues%22%2C%22artist%22%3A%22Velvet%20Revolver%22%2C%22album%22%3A%22Contraband%20(Parental%20Advisory)%22%2C%22albumart%22%3A%22https%3A%2F%2Flh3.googleusercontent.com%2FqUmh8KroLSubCpPB77XFy3WY83SYwuz8JrrEFocE719FFy3DaxH1k6-t7s0h5SkMfTfxvIO-jLNqT5QF%3Dw701-h701-s-l90-rj%22%2C%22playlistId%22%3A%22OLAK5uy_k_IK3hjMTg1CFmNVe3Yvi2nXCLYQsOgjs%22%2C%22autoplayContext%22%3A%7B%22playlistId%22%3A%22OLAK5uy_k_IK3hjMTg1CFmNVe3Yvi2nXCLYQsOgjs%22%2C%22continueFromVideoId%22%3A%22MhJbvagcV6E%22%7D%7D@playlistId=OLAK5uy_k_IK3hjMTg1CFmNVe3Yvi2nXCLYQsOgjs@autoplayContext=%7B%22playlistId%22%3A%22OLAK5uy_k_IK3hjMTg1CFmNVe3Yvi2nXCLYQsOgjs%22%2C%22continueFromVideoId%22%3A%22MhJbvagcV6E%22%7D
InnertubeError: MetadataScreen not found!
This is a bug, please report it at https://github.com/patrickkfkan/Volumio-YouTube.js/issues
    at Function.formatError (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:356:33)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:281:22)
    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:320:53)
    at new SingleColumnMusicWatchNextResults (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/classes/SingleColumnMusicWatchNextResults.js:11:41)
    at Function.parseItem (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:276:32)
    at Function.parse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:320:53)
    at Function.parseResponse (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/parser/index.js:153:33)
    at Music. (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/core/Music.js:185:42)
    at Generator.next ()
    at fulfilled (/data/plugins/music_service/ytmusic/node_modules/volumio-youtubei.js/dist/src/core/Music.js:5:58)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  info: {
    sectionListRenderer: {
      contents: [Array],
      trackingParams: 'CCUQui8iEwiT8qmwyIz8AhVlREwIHdyJDLY='
    }
  },
  date: 2022-12-22T06:10:19.855Z,
  version: '0.1.1-b.2'
}
error: [ytmusic-play] clearAddPlayTrack() error
error: Cannot read property 'as' of null
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0

**Comment by patrickkfkan** [comment]
Closing as this should have been resolved by now. Please reopen if issue persists.
