### ISSUE TITLE
Volumio Web Interface frozen if YTMusic PLugins is enable

### ISSUE THREAD

**Issue by desmphil** [patrickkfkan/volumio-ytmusic#2]
![2023-06-28 09_56_49-Remote Desktop Manager  MAS - VOLUMIO](https://github.com/patrickkfkan/volumio-ytmusic/assets/48382849/c74e2c5e-1c0c-470d-8619-0252cb76c667)
Volumio Web Interface frozen if YTMusic PLugins is enable
I have to delete the plugins from the directory in SSH, then volumio respond again very quickly

If i reinstall the plugins.. the web interface becomes unresponsive.

Like if it was timing out on something forever.
I actually have 4x UNIT on Raspberry PI 4 doing this behavor started 24hours ago

Any idea of logs to gather?
Attached is a screenshot of the journal running

**Comment by desmphil** [comment]
error: [ytmusic] Error in ConfigModel._fetchSettingsPage():  Cannot read property 'session' of undefined TypeError: Cannot read property 'session' of undefined
    at ConfigModel._fetchSettingsPage (/data/plugins/music_service/ytmusic/lib/model/config.js:104:40)
    at ConfigModel.getI18nOptions (/data/plugins/music_service/ytmusic/lib/model/config.js:40:33)
    at ControllerYTMusic.getConfigI18nOptions (/data/plugins/music_service/ytmusic/index.js:230:9)
    at ControllerYTMusic.getUIConfig (/data/plugins/music_service/ytmusic/index.js:34:10)
    at CoreCommandRouter.getUIConfigOnPlugin (/volumio/app/index.js:1088:16)
    at Socket. (/volumio/app/plugins/user_interface/websocket/index.js:329:39)
    at Socket.emit (events.js:315:20)
    at /volumio/node_modules/socket.io/lib/socket.js:503:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by patrickkfkan** [comment]
Hi, I am aware of this. [Same thing with YT plugin](https://community.volumio.com/t/plugin-youtube2/43311/339), which I have fixed. YT Music plugin will be updated shortly.

**Comment by patrickkfkan** [comment]
I have updated the plugin. More info here:

https://community.volumio.com/t/plugin-youtube-music/57647/95

Let me know if the update works for you.

**Comment by patrickkfkan** [comment]
Good to know. I'll close this for now.
